# Generated by Django 4.1 on 2025-11-21 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('navbar_color', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='导航栏颜色')),
                ('user_ID', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='用户ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('nickname', models.CharField(max_length=255, null=True, verbose_name='昵称')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('occupation', models.IntegerField(blank=True, choices=[(0, '其他/未指定'), (1, '学术/教育'), (2, '艺术/娱乐'), (3, '行政/管理'), (4, '大专/技术'), (5, '计算机/程序员'), (6, '医生/医疗'), (7, '技工/修理'), (8, '农民'), (9, '家庭主妇'), (10, '中小学生'), (11, '律师'), (12, '大学生'), (13, '军人'), (14, '退休'), (15, '销售/市场'), (16, '科学家'), (17, '服务业'), (18, '技工/蓝领'), (19, '失业'), (20, '作家')], null=True, verbose_name='职业')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='邮编')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='演员')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movielens_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='MovieLens ID')),
                ('douban_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='豆瓣 ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='电影标题')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='评分')),
                ('date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('poster', models.URLField(blank=True, max_length=500, null=True, verbose_name='海报链接')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('vote_count', models.IntegerField(default=0, verbose_name='评分人数')),
                ('actors', models.ManyToManyField(blank=True, to='myapp.actor', verbose_name='演员列表')),
                ('genres', models.ManyToManyField(blank=True, to='myapp.genre', verbose_name='类型')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'ordering': ['-score', '-vote_count'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='地区')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douban_user_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='豆瓣用户名')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('discussion', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='评分 (1-10)')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='评论影片')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='站内评论用户')),
            ],
            options={
                'verbose_name': '用户评分/评论',
                'verbose_name_plural': '用户评分/评论',
            },
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='推荐度 (预测评分)')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='推荐影片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='推荐用户')),
            ],
            options={
                'verbose_name': '电影推荐',
                'verbose_name_plural': '电影推荐',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='regions',
            field=models.ManyToManyField(blank=True, to='myapp.region', verbose_name='地区'),
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('message', models.TextField(verbose_name='消息内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天记录',
                'verbose_name_plural': '聊天记录',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'movie'), name='unique_site_user_rating'),
        ),
        migrations.AddConstraint(
            model_name='rec',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_recommendation'),
        ),
        migrations.AlterUniqueTogether(
            name='collect',
            unique_together={('user', 'movie')},
        ),
    ]
