# Generated by Django 4.1 on 2025-11-21 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrating',
            name='unique_site_user_rating',
        ),
        migrations.AlterField(
            model_name='userrating',
            name='comment_time',
            field=models.DateTimeField(auto_now=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='电影'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'movie')},
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='douban_user_name',
        ),
    ]
