# Generated by Django 4.1 on 2025-12-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userrating_unique_site_user_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_file',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='本地海报'),
        ),
    ]
