# Generated by Django 4.1 on 2025-12-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_movie_poster_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_sensitive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='敏感内容'),
        ),
        migrations.AddField(
            model_name='movie',
            name='sensitive_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='敏感类型'),
        ),
    ]
