# Generated by Django 4.2.27 on 2025-12-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_movie_is_sensitive_movie_sensitive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='has_mm_features',
            field=models.BooleanField(default=False, verbose_name='已提取多模态特征'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_caption',
            field=models.TextField(blank=True, null=True, verbose_name='[AI] 视觉描述'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_embedding_json',
            field=models.JSONField(blank=True, null=True, verbose_name='[AI] 视觉向量'),
        ),
    ]
