# Generated by Django 4.2.27 on 2026-01-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_movie_has_mm_features_movie_poster_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='douban_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directed_movies', to='myapp.actor', verbose_name='导演'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='IMDB ID'),
        ),
    ]
