# Generated by Django 4.2.29 on 2026-04-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_movie_douban_id_movie_directors_movie_imdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('hybrid', '混合召回'), ('collaborative', '协同过滤'), ('content', '内容推荐'), ('model', '模型推理'), ('agent', 'Agent推荐'), ('hot', '热门兜底'), ('visual', '视觉搜索')], default='hybrid', max_length=32, verbose_name='推荐策略')),
                ('recall_results', models.JSONField(blank=True, null=True, verbose_name='召回结果')),
                ('ranked_results', models.JSONField(blank=True, null=True, verbose_name='精排结果')),
                ('final_results', models.JSONField(blank=True, null=True, verbose_name='最终推荐列表')),
                ('explanations', models.JSONField(blank=True, null=True, verbose_name='推荐理由')),
                ('query_text', models.TextField(blank=True, default='', verbose_name='查询文本')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='总耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '推荐日志',
                'verbose_name_plural': '推荐日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_preferences', models.JSONField(blank=True, default=dict, verbose_name='类型偏好')),
                ('actor_preferences', models.JSONField(blank=True, default=dict, verbose_name='演员偏好')),
                ('director_preferences', models.JSONField(blank=True, default=dict, verbose_name='导演偏好')),
                ('total_ratings', models.IntegerField(default=0, verbose_name='总评分数')),
                ('avg_score', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('total_collections', models.IntegerField(default=0, verbose_name='总收藏数')),
                ('profile_text', models.TextField(blank=True, default='', verbose_name='画像描述')),
                ('is_cold_start', models.BooleanField(default=True, verbose_name='是否冷启动')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户画像',
                'verbose_name_plural': '用户画像',
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, verbose_name='会话ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('agent', 'Agent'), ('system', '系统')], max_length=16, verbose_name='角色')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('intent', models.CharField(blank=True, default='', max_length=64, verbose_name='意图分类')),
                ('agent_trace', models.JSONField(blank=True, help_text='存储 ReAct 范式的 Thought→Action→Observation→Final Answer', null=True, verbose_name='Agent推理链')),
                ('recommended_movie_ids', models.JSONField(blank=True, null=True, verbose_name='推荐电影列表')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='响应耗时(ms)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间戳')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '结构化对话历史',
                'verbose_name_plural': '结构化对话历史',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(verbose_name='用户输入')),
                ('intent', models.CharField(max_length=64, verbose_name='意图分类')),
                ('thought', models.TextField(blank=True, default='', help_text='Agent对用户需求的理解与推理规划', verbose_name='Thought(思考)')),
                ('actions', models.JSONField(blank=True, default=list, help_text='[{"tool": "search_vector", "input": "科幻 高评分", "output": "..."}]', verbose_name='Action(动作列表)')),
                ('observations', models.JSONField(blank=True, default=list, help_text='每个Action对应的执行结果', verbose_name='Observation(观察)')),
                ('final_answer', models.TextField(blank=True, default='', verbose_name='Final Answer(最终答案)')),
                ('recommended_movies', models.JSONField(blank=True, null=True, verbose_name='推荐电影列表')),
                ('explanations', models.JSONField(blank=True, null=True, verbose_name='推荐理由')),
                ('total_latency_ms', models.IntegerField(default=0, verbose_name='总耗时(ms)')),
                ('llm_latency_ms', models.IntegerField(default=0, verbose_name='LLM耗时(ms)')),
                ('tool_latency_ms', models.IntegerField(default=0, verbose_name='工具耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.conversationhistory', verbose_name='关联对话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent推理链',
                'verbose_name_plural': 'Agent推理链',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', '喜欢'), ('dislike', '不喜欢'), ('click', '点击'), ('skip', '跳过'), ('collect', '收藏'), ('share', '分享')], max_length=16, verbose_name='反馈类型')),
                ('source', models.CharField(blank=True, default='', max_length=32, verbose_name='反馈来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='电影')),
                ('recommend_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.recommendlog', verbose_name='关联推荐日志')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'feedback_type'], name='myapp_userf_user_id_ca2056_idx'), models.Index(fields=['movie', 'feedback_type'], name='myapp_userf_movie_i_15e79d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['user', 'session_id'], name='myapp_conve_user_id_76d74a_idx'),
        ),
    ]
